# rift project configuration file

name = "bare-template"

[contracts.bare_template]
    name = "bare-template" # This is the generated target name -> [name].fc
    contract = "BaseContract" # This is the contract class you have in the file
    deploy = "deploy_base" # This is name of the deploy script
    # All test scripts should be mentioned here
    tests = [
        "test_example"
    ]
